[package]
name = "dupdupninja-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "dupdupninja"
path = "src/main.rs"

[dependencies]
dupdupninja-core = { path = "../core" }
