[package]
name = "dupdup-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "dupdup-cli"
path = "src/main.rs"

[dependencies]
dupdup-core = { path = "../core" }

