[package]
name = "dupdup-ffi"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lib]
name = "dupdup_ffi"
crate-type = ["staticlib", "cdylib"]

[dependencies]
dupdup-core = { path = "../core" }
libc = "0.2"

