[package]
name = "dupdupninja-ffi"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lib]
name = "dupdupninja_ffi"
crate-type = ["staticlib", "cdylib"]

[dependencies]
dupdupninja-core = { path = "../core" }
libc = "0.2"
